### PR TITLE
Fix Travis failure for PHP 5.6

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: I almost made the same change in other PR and I was testing it irght now (https://github.com/javiereguiluz/symfony-demo/commit/bf799e4308035e7e07883e58d0628f6ea76c22b3) Thanks!

**Comment by bocharsky-bw** [comment]
Oh, now I see. :)

**Comment by bocharsky-bw** [comment]
I think I could close this PR

**Comment by javiereguiluz** [comment]
Let's wait a bit ... neither your PR nor mine work at the moment :)

**Comment by bocharsky-bw** [comment]
@javiereguiluz The problem was I forgot to update `composer.lock` via `$ composer update`

**Comment by javiereguiluz** [comment]
@bocharsky-bw true! Should we remove the composer.lock file? In Travis the old problems with PHP 5.3 are gone, but now we have new problemas with 5.6 :angry:

**Comment by bocharsky-bw** [comment]
No, `composer.lock` file should be in the repo for same environment for all developers who use this repo. 

The problem is we should always update dependencies when change `composer.json` file via command `$ composer update`. This command generate new `composer.lock` file with new dependencies from `composer.json`

**Comment by javiereguiluz** [comment]
Let's ask for help to our friends @stof and @xabbuh to see if they can tweak the `composer.json` dependencies to fix Travis issues. Thanks!

**Comment by stof** [comment]
The symfony-demo is a project, so we should indeed commit the lock file. See https://github.com/symfony/symfony-demo/commit/0fd26c68ba2fb76346eb914eee4e4c47b5e64920#commitcomment-12339685 for the solution

**Comment by javiereguiluz** [comment]
@stof thanks a lot for your help and for the explanation!!

@bocharsky-bw please add the following in `composer.json`:

```json
"config": {
        "platform": {
            "php": "5.3"
        }
    },
```

Besides, we can remove the `doctrine/dbal` dependency and we can simplify `doctrine/orm` to `~2.4`.

**Comment by bocharsky-bw** [comment]
I had error:

```
  Problem 2
    - symfony/symfony v2.7.2 requires php >=5.3.9 -> your PHP version (5.6.4-4ubuntu6.2) does not satisfy that requirement.
    - symfony/symfony v2.7.2 requires php >=5.3.9 -> your PHP version (5.6.4-4ubuntu6.2) does not satisfy that requirement.
    - symfony/symfony v2.7.1 requires php >=5.3.9 -> your PHP version (5.6.4-4ubuntu6.2) does not satisfy that requirement.
    - symfony/symfony v2.7.0 requires php >=5.3.9 -> your PHP version (5.6.4-4ubuntu6.2) does not satisfy that requirement.
    - Installation request for symfony/symfony ~2.7 -> satisfiable by symfony/symfony[v2.7.0, v2.7.1, v2.7.2].
```
so I bump platform PHP version to `5.3.9`, it's ok?

**Comment by stof** [comment]
@bocharsky-bw yes (and we should change the min version in the symfony-demo composer.json too)

**Comment by bocharsky-bw** [comment]
Still failed

**Comment by bocharsky-bw** [comment]
Looks like old version of `Composer` was a problem :(

**Comment by bocharsky-bw** [comment]
@stof Thanks for your help!

**Comment by javiereguiluz** [comment]
@bocharsky-bw great!!! We finally have green Travis results! Thank you! :tada: :tada: :tada:

**Pull request closed without merging**
