### PR TITLE
Disable html5 validation

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'm trying to understand the reasons of this change. Could you please elaborate a bit? Thanks.

**Comment by bocharsky-bw** [comment]
I guess hason want to disable html5 validation to show users server validation messages.

**Comment by bocharsky-bw** [comment]
But it will be confused developers because main purpose of this project is show best practices way, so they should not disable html5 validation in his projects.

**Comment by bocharsky-bw** [comment]
What about to add comment at the beginning of form open tag (or I think better in form type) with tip that developers could use  `'novalidate' => 'novalidate' } }` or `'required' => false` attributes if they want to see and check server validation messages?
@hason What do you think?

**Comment by javiereguiluz** [comment]
@bocharsky-bw I like your proposal to add a help note about this. I've done that in #100. Thanks.

**Comment by javiereguiluz** [comment]
Closing it in favor of #100

**Pull request closed without merging**
