### PR TITLE
Use new php features

### PR DESCRIPTION
**Pull request by voronkovich**
See https://github.com/symfony/symfony-demo/issues/346

### CODE REVIEW

**Comment by javiereguiluz** [comment]
It feels so nice to use non-prehistoric PHP code! Thanks @voronkovich.

If anyone has other ideas to use PHP 5.5 features in the demo app, please share them!

**Comment by voronkovich** [comment]
Should we use:
```php
$entityManager->getRepository(User::class)
```
instead of:
```php
$entityManager->getRepository('AppBundle:User')
```
?

**Comment by stof** [comment]
@voronkovich I would say yes. ``AppBundle:`` shortcuts would probably not be implemented in Doctrine if the project started today.

**Comment by voronkovich** [comment]
@stof, I agree with you. I've changed the code.

**Comment by javiereguiluz** [comment]
@voronkovich thanks for working on this. The next version of the app not only will use Symfony 3.1 but also PHP 5.5!

**Pull request closed without merging**
