### PR TITLE
Merge pull request #1 from symfony/master

### PR DESCRIPTION
**Pull request by rasanga**
merge symfony/symfon-demo master

### CODE REVIEW

**Comment by stof** [comment]
This PR does not make sense

**Comment by rasanga** [comment]
Sorry, I mistakenly made it

**Comment by xabbuh** [comment]
@rasanga Can you this then please?

**Comment by rasanga** [comment]
@xabbuh Sorry, I didn't understand, I could not delete this PR

**Comment by xabbuh** [comment]
No need to delete it. You can simply close it.

**Pull request closed without merging**
