### PR TITLE
Mention to create .env file before running this application

### PR DESCRIPTION
**Pull request by bocharsky-bw**
After `git pull` and `composer install` I was not able to run this application due to the lack of `.env` file.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks for your report ... but I'm afraid we can't accept this PR. The promise we made since day one was that the Symfony Demo app could be run just after installing it without the need to execute any command, add/modify any config or do anything at all. So we must consider this as a bug.

Can anybody think of a better solution that committing the `.env` file to the repo? Thanks!

**Comment by bocharsky-bw** [comment]
I think the best way is to load `.env.dist` file by default in `index.php` if no `.env` exists. Or, we can consider adding a Composer script to actual copy `.env.dist` -> `.env` on composer install/update if not exists

**Comment by yceruto** [comment]
I think it's an issue that could be fixed by symfony/flex in `EnvConfigurator`:

https://github.com/symfony/flex/blob/17e56322f33990daa08cf5761c80188b3a2b41b1/src/Configurator/EnvConfigurator.php#L21-L48

I mean, in a fresh install it's copied from `.env.dist` automatically BUT when we're cloning a project that already has `.env.dist` file updated (no changes regarding recipe) then `.env` file is not created. So in the next `composer require <package-with-recipe>` if they are changes in `.env.dist` then `.env` file is created.

**Comment by yceruto** [comment]
and same here if the original lock hash and composer lock hash doesn't has been changed:

https://github.com/symfony/flex/blob/17e56322f33990daa08cf5761c80188b3a2b41b1/src/Flex.php#L140-L147

**Comment by fabpot** [comment]
Good analysis @yceruto. Fixed in Flex 1.0.17. So, when demo is upgraded to that version, it will fix this issue.

**Comment by javiereguiluz** [comment]
Closing in favor of #638.

**Pull request closed without merging**
