### PR TITLE
Simplify comment creating functional test

### PR DESCRIPTION
**Pull request by voronkovich**
Current test is not truly "functional" because it knows too much about internal structure of an application.

@dmaicher, this test pass only when I disable the `PHPUnitStaticDbConnectionListener`. Could you please look at the code?

### CODE REVIEW

**Comment by dmaicher** [comment]
Thanks for the report :wink: I actually think I found the problem which lies inside `dama/doctrine-test-bundle`.

I will look into this tomorrow and will let you know asap.

**Comment by dmaicher** [comment]
@voronkovich there is a new release that fixes the problem :wink: 

https://github.com/dmaicher/doctrine-test-bundle/releases/tag/v1.0.12

So if you run `composer update dama/doctrine-test-bundle` and commit the changes the build should pass.

**Comment by voronkovich** [comment]
@dmaicher, test passes! Thank you very much!

**Comment by javiereguiluz** [comment]
@voronkovich thanks for simplifying this test. I like it!

**Pull request closed without merging**
