### PR TITLE
Add missing Ukrainian translation

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Add missing `label.save_and_create_new` for Ukrainian translation

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks for fixing this translation. Cheers from the SymfonyCon Paris 2015 Hackday :)

**Comment by bocharsky-bw** [comment]
@javiereguiluz Thanks! Have a nice Hackday today! :)

> [For Symfony’s 10th birthday, we want to organize something special! To be announced soon, stay tuned!](http://pariscon2015.symfony.com/hackday)

Do you already know what's "something special" exactly was organized for Symfony’s 10th birthday? ;)

**Comment by javiereguiluz** [comment]
@bocharsky-bw sadly I know nothing about that "special thing" that you mentioned :(

**Comment by bocharsky-bw** [comment]
Hm, maybe you will know later ;)

**Pull request merged**
