### PR TITLE
Updated the demo application to Symfony 2.7

### LINKED ISSUE #71: Update demo to SF 2.7
Hi guys!,

How about updating SF to 2.7 in sake of consistency between docs ? . BR

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #71

### CODE REVIEW

**Comment by xabbuh** [comment]
You should also commit the changes to the `composer.json` file.

**Comment by javiereguiluz** [comment]
@xabbuh I did ... there is none :)

**Comment by xabbuh** [comment]
But there should be a difference if you bump the requirement to Symfony 2.7.

**Comment by javiereguiluz** [comment]
@xabbuh in the `.lock` file yes, but not in the `.json` file (we use `~2.6` for Symfony)

**Comment by javiereguiluz** [comment]
By the way, I updated Symfony following the recommendation of @weaverryan:

```bash
$ composer update symfony/symfony sensio/distribution-bundle --with-dependencies
```

**Comment by xabbuh** [comment]
To be more clear: You now make use of the `configureOptions()` method which introduced in Symfony 2.7. So having a version constraint like that if wing as you cannot use the form types with Symfony 2.6.

**Comment by javiereguiluz** [comment]
OK. I understand you now :)  Should I use `2.7.*` or `~2.7`?

**Comment by xabbuh** [comment]
Not sure if that really matters. What was the reasoning for the old constraint?

**Comment by javiereguiluz** [comment]
There was no particular reasoning. I always use the `~` constraint, so let's keep using `~2.7`. Thanks.

**Comment by stof** [comment]
@javiereguiluz what about updating other deps too (DoctrineBundle got a new release for instance)

**Comment by javiereguiluz** [comment]
@stof I fully agree!  The constraint is now `~1.5` and I've executed `composer update doctrine/doctrine-bundle --with-dependencies`

The current constraints are as follows. Should we update any other dependency?

```json
    "require": {
        "php"                                  : ">=5.3.3",
        "ext-pdo_sqlite"                       : "*",
        "doctrine/doctrine-bundle"             : "~1.5",
        "doctrine/doctrine-fixtures-bundle"    : "~2.2",
        "doctrine/orm"                         : "~2.2,>=2.2.3",
        "erusev/parsedown"                     : "~1.5",
        "incenteev/composer-parameter-handler" : "~2.0",
        "ircmaxell/password-compat"            : "~1.0",
        "leafo/scssphp"                        : "~0.1.",
        "patchwork/jsqueeze"                   : "~1.0",
        "sensio/distribution-bundle"           : "~3.0.12",
        "sensio/framework-extra-bundle"        : "~3.0",
        "symfony/assetic-bundle"               : "~2.3",
        "symfony/monolog-bundle"               : "~2.4",
        "symfony/swiftmailer-bundle"           : "~2.3",
        "symfony/symfony"                      : "~2.7",
        "twig/extensions"                      : "~1.0"
    },
```

**Comment by stof** [comment]
Well, you should probably update all deps to their latest stable versions (``incenteev/composer-parameter-handler`` has a new release too to avoid deprecation warnings on Symfony 2.7 for instance)

**Comment by javiereguiluz** [comment]
OK then. I've updated everything to their latest versions.

**Comment by weaverryan** [comment]
btw, we used the `2.6.*` format in `composer.json` for `symfony/symfony` just to match the SE. But I don't think it's a problem to differ from it - as long as we're doing something "good" :).

**Comment by weaverryan** [comment]
:+1:

**Comment by weaverryan** [comment]
@javiereguiluz for the future - I had an idea. We could upgrade a branch of the `symfony-demo` during the stabilization phase of a Symfony version. Then, it'll be ready for the release. But more importantly, it might help identify any bugs or not-smooth upgrade paths, while those can still be fixed :).

**Comment by javiereguiluz** [comment]
@weaverryan I like the idea and I'm going to implement it for 2.8. Thanks!

**Pull request closed without merging**
