### PR TITLE
Use proper database in a test environment

### PR DESCRIPTION
**Pull request by voronkovich**
See https://github.com/symfony/symfony-demo/issues/556

### CODE REVIEW

**Comment by voronkovich** [comment]
@stof, I replaced a test database `path` by `url`, but now it throws an exception: `Incompatible use of dynamic environment variables "DATABASE_URL" found in parameters.` in test environment.

**Comment by dmaicher** [comment]
We could just provide the environment variable in the phpunit config:

```xml
<php>
    ...
    <env name="DATABASE_URL" value="sqlite:///%kernel.root_dir%/../var/data/blog_test.sqlite" />
</php>
```
This works.

**Comment by dmaicher** [comment]
@stof @javiereguiluz what do you think? Specifying the environment variable like that seems the easiest to me.

**Comment by voronkovich** [comment]
Closed in favor of #572

**Pull request closed without merging**
