### PR TITLE
Make the application name translatable

### PR DESCRIPTION
**Pull request by davialexandre**
While I was doing the Brazilian Portuguese translation I realized that the application name on the page title and on the navbar couldn't be translated. Since it is a descriptive name, I think it would be nice for it to be translatable.

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
I don't think it's a good idea. I prefer to left it untranslatable as static project name.

**Comment by davialexandre** [comment]
To me it sounds more like a descriptive name than a brand. Also, it has already been translated to French and Spanish (in the title.homepage message).

**Comment by javiereguiluz** [comment]
I'm also divided about this. Using "Symfony Demo Application" for all languages is better for our branding. But displaying "Symfony Demo Application" in any language different from English may seem weird.

I definitely need to read more opinions from other developers. Let's see what does the community think about this.

**Comment by javiereguiluz** [comment]
After musing about this issue, I think it's better to maintain the "Symfony Demo" name for all languages. However, I also think we can improve the current situation. Right now we call this app the "Symfony Demo Application". We could rename it just to "Symfony Demo" application.

### Before

before_1

### After

after_1

### Before

before_2

### After

after_2

**Comment by bocharsky-bw** [comment]
Great compromise! It's much more clearer. I like it :+1:

**Comment by javiereguiluz** [comment]
The changes have been done in #101.

**Comment by davialexandre** [comment]
Nice! 👍

**Pull request closed without merging**
