### PR TITLE
Remove "ircmaxell/password-compat" package

### PR DESCRIPTION
**Pull request by chapay**
We don't need this package after the switch to PHP 5.5.

### CODE REVIEW

**Comment by xabbuh** [comment]
I wonder if the `hash` property in the `composer.lock` file shouldn't have changed too.

**Comment by chapay** [comment]
Changed it, thanks!

**Comment by xabbuh** [comment]
👍

**Comment by javiereguiluz** [comment]
👍

**Comment by javiereguiluz** [comment]
Thank you @chapay.

**Pull request closed without merging**
