### PR TITLE
Updated dependencies for Symfony 2.8.5

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Hey, this PR update Symfony up to `v2.8.5` only

**Comment by stof** [comment]
@javiereguiluz updating the commit message and the PR title would be a good idea.

**Comment by javiereguiluz** [comment]
@bocharsky-bw 😱 😱 😱 I don't know what I was thinking. I'm closing this PR. Will you send a PR for 2.8.5 as you usually do? thanks!

**Comment by javiereguiluz** [comment]
Sorry for the noise!  I was using the Symfony Demo to test Symfony 3.1 (to write the blog posts, to test the Cache component, etc.)  So I made lots of changes in the composer.json file and the app and then reverted everything and I wasn't sure if I had updated to 2.8.x or 3.x.

**Pull request merged**
