### PR TITLE
German pagination control translations

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
By the way: should we add them to the English file too in case someone uses it as a reference to search for missing translations in their language?

**Comment by xabbuh** [comment]
ping @OskarStark

**Comment by stof** [comment]
IMO, we should have all translations in the English files, yes. this way, you can easily find missing ones

**Comment by xabbuh** [comment]
see #233

**Comment by OskarStark** [comment]
:+1: @xabbuh, but i would like to use translations keys, instead of translating the language directly.

``previous_label`` or ``label_previous``

Oskar

**Comment by xabbuh** [comment]
@OskarStark We can't control that (the string to be translated comes from a third-party library).

**Comment by OskarStark** [comment]
oh, didn't know that :+1:

**Comment by javiereguiluz** [comment]
Thanks @xabbuh.

**Pull request merged**
