### PR TITLE
Delete all post/tag entries on delete a Post

### PR DESCRIPTION
**Pull request by yceruto**
We can't use cascade delete constraint in this case because Foreign key support is not enabled in SQLite by default. (https://www.sqlite.org/foreignkeys.html#fk_enable)

More information about it:
- https://github.com/doctrine/dbal/issues/2104
- https://github.com/doctrine/dbal/issues/1204

So my only one solution was to clear this relations manually.

### CODE REVIEW

**Comment by voronkovich** [comment]
@yceruto , IMO it is a platform-specific issue, so we shouldn't fix it in the demo application.

**Comment by javiereguiluz** [comment]
I tend to agree with @voronkovich ... it may be even confusing for newcomers and they might think that they always need to do this.

**Comment by yceruto** [comment]
I'm agree that it's platform-specific issue, but it's the default one, so currently this works wrong for newcomers. We can insert a comment about this then? Something like:
```
// This is necessary for SQLite platform only, you can remove it for another platform.
$post->getTags()->clear();
```
What do you think?

**Comment by yceruto** [comment]
I'm also thinking when we need to test the Post "Delete/New" actions, if won't fix that, then the SQLite DB will have an invalid state.

**Comment by javiereguiluz** [comment]
Let's merge this with the help note. Thanks @yceruto!

**Pull request merged**
