### PR TITLE
Add underscore prefix to the template that not extend base one

### PR DESCRIPTION
**Pull request by bocharsky-bw**
It seems we add "_" prefix to the name of all templates that not extend the base one.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
The `_` is added to any template fragment which is included in other templates. So I'm :+1: to this change.

**Comment by bocharsky-bw** [comment]
Yes, it make sense. Ryan use it in his [screencasts](http://knpuniversity.com/screencast/twig/including-other-templates#using-the-include-function) too

**Comment by javiereguiluz** [comment]
Thanks for all your work on this project!

**Comment by bocharsky-bw** [comment]
I love Symfony! :)

**Pull request merged**
