### PR TITLE
Fixed form errors for comment

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Can you please post a screenshot of the change? For comparison, this is how errors look right now:

form_error

**Comment by hason** [comment]
Before:
image

After:
image

**Comment by javiereguiluz** [comment]
OK. The change only affects the `comment` form. I missed that. Sorry. Your change looks good to me :+1: Thanks.

**Comment by javiereguiluz** [comment]
Thanks for fixing this bug @hason.

**Pull request merged**
