### PR TITLE
Add translation to pager

### PR DESCRIPTION
**Pull request by krewetka**
Pager was always in English

### CODE REVIEW

**Comment by krewetka** [comment]
Removed unnecessary previous & next translations

**Comment by javiereguiluz** [comment]
@krewetka thanks for this contribution! I've tested it locally and it works like a charm. BEfore merging your pull request I've "squashed" your commits. That's why GitHub displays this pull request as "closed" instead of "merged" ... but it's merged :)

**Comment by krewetka** [comment]
You're welcome :)

I knew it's not the best way to make it in separate commits but I haven't find other option on the website and I didn't have time to make it in proper way with downloading it to computer and so on/

**Comment by javiereguiluz** [comment]
@krewetka no worries. I also prefer to make small commits and at the end everything is squashed into a single commit. Luckily the tool we use to merge pull requests does the squashing automatically, so that's why we never ask committers to do anything about that. Thanks!

**Pull request closed without merging**
