### PR TITLE
Improve the checking if the current request is a master request in the ControllerListener.

### PR DESCRIPTION
**Pull request by voronkovich**
There is a more convenient way to check whether the current request is a master request. See http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Event/KernelEvent.html#method_isMasterRequest

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@voronkovich thanks for this improvement. I do agree with you that this proposal is much better. You don't need to know the internal Symfony details when you are learning Symfony.

In any case, before merging it, I'll wait a bit so others can comment if they don't agree or see some drawback. Cheers!

**Comment by JulienItard** [comment]
I agree with it because it's more readable and less "frigthening" for beginners.

**Comment by weaverryan** [comment]
:+1:

**Comment by javiereguiluz** [comment]
@voronkovich thanks for helping us improve the code of the Symfony Demo application!:wq!

**Pull request merged**
