### PR TITLE
Upgraded the application to Symfony 3.2.0

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
After upgrading, I see the following deprecation log in every page:

32rc2_deprecation

**Comment by jzawadzki** [comment]
@javiereguiluz it looks like it's fixed in symfony/monolog-bundle v2.12 (by https://github.com/symfony/monolog-bundle/commit/a55b0a098951dcab5d902726a8b1579053e1b1d0#diff-25076ecfab002a680c691e32a36c5e6bL106) - currently composer installs v2.11.3

**Comment by javiereguiluz** [comment]
@jzawadzki you are right! I've updated all dependencies and the deprecation log is gone. Thanks!

**Comment by dzuelke** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by bocharsky-bw** [comment]
Let's update to v3.2.0

**Pull request closed without merging**
