### PR TITLE
Make Twig services and event listeners private

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Thanks to stof in https://github.com/symfony/symfony-demo/pull/104#discussion_r35083734

### CODE REVIEW

**Comment by stof** [comment]
Listeners cannot be private. they are access dynamically to lazy-load them (you should be getting an exception during the container building btw).

@javiereguiluz what about enabling Travis on the repo to run the tests ?

**Comment by javiereguiluz** [comment]
Thanks @bocharsky-bw for sending PRs, reviewing code and being so active on this repository!

**Comment by stof** [comment]
The markdown service should be private too btw, for the same reason than Twig extensions (it is only used as a dependency of the twig extension)

**Comment by stof** [comment]
@javiereguiluz you merged a broken PR

**Comment by javiereguiluz** [comment]
You are right! It was fixed on https://github.com/symfony/symfony-demo/commit/360834879f99cee876815952256e4b94087eccb7

**Comment by javiereguiluz** [comment]
Travis is set up in the `.travis.yml` but I don't have permissions to do the needed changes in the repository config :(

**Comment by stof** [comment]
@fabpot can you enable Travis on this repo ?

**Comment by bocharsky-bw** [comment]
@stof and @javiereguiluz thank you!

**Comment by fabpot** [comment]
@stof done

**Pull request merged**
