### PR TITLE
Add to the readme a note about how to run the application in production environment

### PR DESCRIPTION
**Pull request by voronkovich**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by xabbuh** [comment]
I am :-1: here. Adding this note adds the misleading impression that it might be a good idea to run PHP's built-in web server in production environments.

**Comment by bocharsky-bw** [comment]
@xabbuh You have a point there. What about to add more commets, for example, never use it in prodaction and use only for developing things like checking custom error pages, etc. What do you think?

**Comment by javiereguiluz** [comment]
Another argument against adding this change would be that we want this application to always being executed on `dev` environment. Why? Because this app is for newcomers and for learning purposes. It makes sense in those scenarios to use the toolbar + profiler (moreover when we've just redesigning them from scratch).

**Comment by voronkovich** [comment]
@javiereguiluz, I think newcomers should know about differences between `prod` and `dev` environments.

**Comment by voronkovich** [comment]
Imgur

**Comment by javiereguiluz** [comment]
@voronkovich your last screenshot is definitive to me :)  I don't think it's right to mention something that we explicitly discourage or not recommend. That's why I'm closing this pull request without merging it. Thanks for understanding it.

**Pull request closed without merging**
