### PR TITLE
Use cache.adapter.apcu instead of deprecated validator and serializer

### PR DESCRIPTION
**Pull request by bocharsky-bw**
According to the https://github.com/symfony/symfony-standard/pull/965

### CODE REVIEW

**Comment by xabbuh** [comment]
We need to wait with merging this until the demo switched to Symfony 3.1.

**Comment by bocharsky-bw** [comment]
I'm wondering when do we plan to switch on Symfony 3.x?

**Comment by javiereguiluz** [comment]
The master branch is now Symfony 3.1.

**Comment by javiereguiluz** [comment]
Should we merge this as it is now? Thanks.

**Comment by stof** [comment]
:+1:

**Comment by javiereguiluz** [comment]
@bocharsky-bw it's merged now. Thanks!

**Pull request merged**
