### PR TITLE
Use css flexbox for sticky footer.

### PR DESCRIPTION
**Pull request by ogizanagi**
screenshot 2015-06-28 a 09 45 51

### CODE REVIEW

**Comment by JulienItard** [comment]
:+1:

**Comment by xabbuh** [comment]
@ogizanagi Can you provide a screenshot of how it would look like then?

**Comment by ogizanagi** [comment]
screenshot 2015-06-28 a 09 45 51

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Awesome! this is what I always wanted to do ... but never know how to do it. Thanks @ogizanagi

**Pull request merged**
