### PR TITLE
Added a fallback Twig extension when PHP's intl is not available

### LINKED ISSUE #329: Don't use localizeddate to avoid Intl errors
I didn't have a supported timezone setting in my PHP.ini, resulting in the following exception:

 > An exception has been thrown during the rendering of a template ("Time zone different than GMT or UTC is not supported as a formatting output. Please install the "intl" extension for full localization capabilities.") in base.html.twig at line 150.

I think this will be a common issue for  Windows users. As this demo should work straightaway, I propose to remove `|localizeddate` from the templates and simply replace them by `|date('r')` or the like.

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #329.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@mtsanford @tcicit @WouterJ could you please try the changes proposed in this pull request to see if it solves your problems with Windows + Intl? Thanks!

**Comment by tcicit** [comment]
I can not find the file. In the demo app, there are only the following file: "\symfony_demo\src\AppBundle\Twig\AppExtension.php".

**Comment by bocharsky-bw** [comment]
You should checkout on `fix_329` branch of the https://github.com/javiereguiluz/symfony-demo Javier's fork repo.

**Comment by javiereguiluz** [comment]
@tcicit if you don't want to mess with Git, you can recreate these changes in your own computer. It's just a matter of creating 2 files and modifying 2 other files. See: https://github.com/symfony/symfony-demo/pull/335/files

**Comment by WouterJ** [comment]
While this is probably works fine (didn't test it yet), I think the implementation is very complex (especially for a *demo* app for beginners):

 * Using PHP config to register the service
 * A full-blown polyfill for intl date formatter

What about creating a `render_date()` function? This would allow us to get rid of both problems, makes the implementation quite a lot simpler (as it's just `intl_enabled ? IntlDateFormatter::create(...)->format(new \DateTime()) : date(...);`) and also shows how readable you can make your templates by adding some very tiny functions and filters.

**Comment by javiereguiluz** [comment]
Closed in favor of #344.

**Pull request closed without merging**
