### PR TITLE
feature #240 Update Dependencies

### PR DESCRIPTION
**Pull request by tonylds1**
[web] [config.php] this file is updated by composer.json script

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
:-1: This script was customized for Symfony Demo app

**Comment by javiereguiluz** [comment]
@tonylds1 you are right, but this project uses a customized script because the Symfony script is a bit ugly and ours is better integrated with the overall design of the application.

By the way, anyone knows how could we prevent further issues related to this script? How can ignore the default Symfony script forever?

**Comment by voronkovich** [comment]
@javiereguiluz,  we could add it to .gitignore

**Comment by javiereguiluz** [comment]
@voronkovich yes, but the main problem is that when you execute `composer update`, our script is overridden by the default script.

**Comment by voronkovich** [comment]
@javiereguiluz, I think the main problem is that every month somebody creates a PR with the updated `config.php`. :)

**Comment by javiereguiluz** [comment]
A solution could be to redesign the original config.php so it sucks less. After all, we've already redesigned most of the Symfony elements.

**Comment by voronkovich** [comment]
@javiereguiluz, I think we could add a command `git checkout web/config.php` to the `post-update-cmd` section of the composer.json

**Comment by voronkovich** [comment]
@javiereguiluz what about to rename `config.php`?
See https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L216

**Comment by javiereguiluz** [comment]
@voronkovich we did that in the past ... and @bocharsky-bw still has nightmares about that ;)

**Comment by bocharsky-bw** [comment]
Yeah, `app/check.php` script refers exactly to the `config.php`. It was in https://github.com/symfony/symfony-demo/pull/140 :)

**Comment by voronkovich** [comment]
I think we could use a dirty hack, like this:
```json
"post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "mv web/config.php web/_config.php",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "mv web/_config.php web/config.php",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ]
```

**Comment by javiereguiluz** [comment]
Let's close this issue as "won't fix" for now and we'll revisit it when Symfony 2.8 and 3.0 are released. Thanks!

**Pull request closed without merging**
