### PR TITLE
Move Heroku deploy button to the installation section

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Minor changes in the README.md

### CODE REVIEW

**Comment by stof** [comment]
The badge is still on the same line though

**Comment by bocharsky-bw** [comment]
@stof I meant here that Heroku button is on line 7 and Travis badge is on line 8 in a source code. Do you think we should place them both on the separate lines in rendered view?

**Comment by voronkovich** [comment]
@bocharsky-bw, what about to move this button to the "installation" section?

**Comment by bocharsky-bw** [comment]
Move Heroku deploy button to the Installation section is a good idea, I think.

**Comment by javiereguiluz** [comment]
I agree with @voronkovich: let's move Heroku button to Install section.

**Comment by bocharsky-bw** [comment]
:+1: Done!

**Comment by javiereguiluz** [comment]
Thank you @bocharsky-bw.

**Pull request merged**
