### PR TITLE
Move PHPUnit tests folder into the root folder

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by javiereguiluz** [comment]
I agree with this change, but I'd like to read other opinions. Apparently, Symfony doesn't recommend this practice officially.

**Comment by bocharsky-bw** [comment]
I'm wondering to hear other opinions too. BTW, `symfony-standard` already moved `DefaultControllerTest` into the `tests` directory:
https://github.com/symfony/symfony-standard/blob/master/tests/AppBundle/Controller/DefaultControllerTest.php

**Comment by voronkovich** [comment]
I think that holding the folder with tests in the root directory just makes it easier to launch the tests: `phpunit` vs. `phpunit -c app`. :+1:

**Comment by javiereguiluz** [comment]
@voronkovich good point ... but if I'm right, that's achieved by moving the `phpunit.xml.dist` config file to the root directory. That's what Symfony 3.x did and we can run the tests with `phpunit` even if they are located inside `src/`

**Comment by voronkovich** [comment]
@javiereguiluz,  you're right, I mistakenly confused the test directory and phpunit.xml file. So, I don't have any opinion about this PR :(

**Comment by voronkovich** [comment]
@javiereguiluz, there is an explanation why tests folder was moved to the root directory in the symfony-standard. See https://github.com/symfony/symfony-standard/commit/d0311d2eb06309d9fc0b8bacb8cab9e0f29c622f#commitcomment-15653984

**Comment by xabbuh** [comment]
The namespace of the `SluggerTest` class needs to be updated too.

**Comment by bocharsky-bw** [comment]
@xabbuh Yes, I know. It's weird, but it already has correct namespace in [master](https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Tests/Utils/SluggerTest.php#L12).

**Comment by xabbuh** [comment]
@bocharsky-bw But the namespace should be `Tests\AppBundle\Utils` and the location should be updated accordingly.

**Comment by xabbuh** [comment]
And to be consistent with the Symfony Standard Edition we would need to have a `tests/AppBundle` directory.

**Comment by bocharsky-bw** [comment]
@xabbuh Ah, you're totally right, I missed `AppBundle`.

Thanks for notice it! I'll fix it soon.

**Comment by bocharsky-bw** [comment]
Done.

**Comment by xabbuh** [comment]
👍

**Comment by javiereguiluz** [comment]
Thank you @bocharsky-bw.

**Pull request closed without merging**
