### PR TITLE
Removed the unused SwiftMailerBundle

### PR DESCRIPTION
**Pull request by javiereguiluz**
Related to #417 and created to see if the community agrees or not with this change. Thanks!

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
There's some Swiftmailer code in `config_dev.yml` and `config_test.yml` files.

**Comment by bocharsky-bw** [comment]
IMO, since it comes out-of-the-box with Symfony SE I'd rather add a simple example of its usage instead of remove it at all.

**Comment by javiereguiluz** [comment]
One of the main problems is that we want the Symfony Demo fully working ... and you can't do that with SwiftMailer. We can't make SwiftMailer work and send emails for our users, because that means that they need to add some config parameters in the application with their Gmail or mail server credentials.

**Comment by bocharsky-bw** [comment]
I mean using [The Mail Transport](http://swiftmailer.org/docs/sending.html#the-mail-transport), i.e. native PHP mail() function for sending emails, but as I see, it has some issues too, so probably removing Swiftmailer is the best option here 👍

**Comment by javiereguiluz** [comment]
@bocharsky-bw problem is that the mail transport has been deprecated and it will be removed soon: https://github.com/swiftmailer/swiftmailer/commit/905b0bca8acf359dad3dfc2bc298c56de922cd57

**Comment by voronkovich** [comment]
@javiereguiluz, we can disable email sendig in the configuration
```yaml
swiftmailer:
    disable_delivery:  true
```

**Comment by javiereguiluz** [comment]
@voronkovich yes ... but actually I'm looking for the opposite. If we want to showcase the SwiftMailer feature ... then the email sending must work and developers must receive some emails somewhere.

**Comment by bocharsky-bw** [comment]
@javiereguiluz Ah, then it makes even more sense... thanks!

**Comment by frastel** [comment]
Seeing the Mails in the Web Debug Toolbar is not enough?

**Comment by voronkovich** [comment]
@javiereguiluz, developers can view the sent email in the debug toolbar
http://symfony.com/doc/current/email/dev_environment.html#viewing-from-the-web-debug-toolbar

**Comment by javiereguiluz** [comment]
@voronkovich you are right! Maybe some "fake sending" is enough to showcase this feature.

**Comment by javiereguiluz** [comment]
Closing in favor of other PRs that will make use of the SwiftMailer bundle.

**Pull request closed without merging**
