### PR TITLE
Add check.php file for access from web

### PR DESCRIPTION
**Pull request by javiereguiluz**
This PR takes the work made by @bocharsky-bw in #74 and applies the look-and-feel of the Symfony Demo application to better integrate it.

### No errors - Before

before_ok

### No errors - After

after-ok

### Errors - Before

before-ko

### Errors - After

after-ko

### CODE REVIEW

**Comment by OskarStark** [comment]
i think the symfony logo should be integrated

**Comment by bocharsky-bw** [comment]
@javiereguiluz Thanks a lot! I like it :+1:

**Comment by bocharsky-bw** [comment]
@OskarStark There is no Symfony's logo in `Symfony Demo Application`, so I think it will be unnecessary for this PR

**Comment by javiereguiluz** [comment]
@OskarStark I think the Symfony logo should be reserved for the Symfony installation. This demo is independent from the framework, so I think we can change its design to match our styles.

**Comment by OskarStark** [comment]
yes but the name ```Symfony```is used everywhere...

**Comment by javiereguiluz** [comment]
@OskarStark let me put my reasoning in other words: this app is "made with Symfony" but "it's not Symfony". But let's see if other developers think we should add the logo.

**Comment by OskarStark** [comment]
@javiereguiluz i understand your reasoning, but i think this is an app which shows best practices by the symfony community with standard symfony edition... so a logo makes it more clear.... before this pr there was a symfony logo, or?

**Comment by javiereguiluz** [comment]
@bocharsky-bw I agree. Done. Thanks.

**Comment by bocharsky-bw** [comment]
@OskarStark I think better to create a new issue for this discussion about Symfony's logo in order to other developers could also tell their opinion.

**Comment by bocharsky-bw** [comment]
@javiereguiluz What about to add some instructions to `README.md` about usage of this `check.php` at the beginning?

**Comment by javiereguiluz** [comment]
@bocharsky-bw I like the idea a lot. Done in d88ef7b

**Comment by OskarStark** [comment]
:+1:  for the note

**Comment by xabbuh** [comment]
What about renaming the file to `config.php`? Then its name is consistent with the one from the Standard Edition.

**Comment by bocharsky-bw** [comment]
@xabbuh I think about it too, but there are no any config operations, only environment checks, so it seems to confused a bit as for me.

**Comment by javiereguiluz** [comment]
This feature is now merged. Thank you @bocharsky-bw for starting it and thank you all for the reviews and the discussion!

**Pull request merged**
