### PR TITLE
Enforce best pratices for form button

### PR DESCRIPTION
**Pull request by b-durand**
See http://symfony.com/doc/current/best_practices/forms.html#form-button-configuration.

One more thing: fix missing translation for a hidden label in the same view.

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Yes, it's true :+1: . However I like form buttons because it allows to do in controllers something like:

``` php
// create/update action
if ($form->get('save_and_close')->isClicked()) {
    return $this->redirectToRoute('post');
}

return $this->redirectToRoute('post_edit', ['id' => $entity->getId()]);
```

**Comment by voronkovich** [comment]
I think you should remove the `createCommentForm` method, because it's unnecessary

**Comment by bocharsky-bw** [comment]
Yes, to be consistent with other forms creation in this demo

**Comment by javiereguiluz** [comment]
It took a while but this is finally merged. Thanks @b-durand

**Pull request closed without merging**
