### PR TITLE
Fix invalid xliff for Ukrainian translation

### PR DESCRIPTION
**Pull request by bocharsky-bw**
I'm sorry, it's my fault! I missed it in https://github.com/symfony/symfony-demo/pull/284 :(

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@bocharsky-bw no worries! I missed it too during the review. Thanks for the quick fix.

**Comment by xabbuh** [comment]
@javiereguiluz What about adding a test that validates the translation files?

**Comment by bocharsky-bw** [comment]
@xabbuh  :+1:

**Comment by javiereguiluz** [comment]
We could define a ver simple "smoke test" that loads the homepage in all the available translations.

**Pull request merged**
