### PR TITLE
Enabled the PHP CS rule to fix the file header comment

### PR DESCRIPTION
**Pull request by javiereguiluz**
To avoid issues like #510.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Now the tests fail because the PHP files in `app/` and `web/` don't have this header. We won't add it to those files, so how can we solve this?

**Comment by apetitpa** [comment]
Add `->notPath('web/app_dev.php')` etc to the $finder in .php_cs file ?

**Comment by javiereguiluz** [comment]
Yes ... but we want the rest of the rules applied to app/ and web/ files :(

**Comment by apetitpa** [comment]
I don't think there is a way to excluse some checks for a particular path. Maybe this could be a new feature.

**Comment by yceruto** [comment]
@javiereguiluz if we let the license be included in these files?

**Comment by javiereguiluz** [comment]
@yceruto let's do that because I honestly see no other solution.

**Pull request closed without merging**
