### PR TITLE
Use a custom variable for getting the current Twig template instance

### PR DESCRIPTION
**Pull request by voronkovich**
This PR fixes https://github.com/symfony/symfony-demo/issues/242

### CODE REVIEW

**Comment by javiereguiluz** [comment]
The proposed solution is great ... although maybe too complex? I was thinking about solving this issue as:

```twig
{% import _self as current_template %}
{{ show_source_code(current_template) }}
```

But I guess @voronkovich's solution is more professional :)

**Comment by voronkovich** [comment]
@javiereguiluz, yeah, it's an enterprise level solution! :)

**Comment by javiereguiluz** [comment]
I'm reopening the pull request because I think it might be a good solution. It's complex ... but that doesn't mean it's bad. Maybe we could use it to show advanced Twig features. Let's wait to hear more opinions about this. Thanks.

**Comment by stof** [comment]
@javiereguiluz the issue of your proposal is that it abuses the import tag (Twig 2 might change the way macros are imported, forbidding this again).
This PR matches my initial idea, except that I wanted to avoid giving such power to anyone (the current code duplicates the deprecated ``_self`` behavior for anyone, but with a different variable name)
I then thought about another way, which would solve other needs for which the removal of ``_self`` is painful, and I opened the discussion on twig (which is why I haven't opened a PR on the demo yet): https://github.com/twigphp/Twig/issues/1932

**Comment by javiereguiluz** [comment]
Closing it in favor of #254 ( although I don't know if that would be the definitive solution either).

**Pull request closed without merging**
