### PR TITLE
Update Russian translations

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for updating this translation. Before merging it, we'd also need to create a new `validators.ru.xliff` to translate https://github.com/symfony/symfony-demo/blob/master/app/Resources/translations/validators.en.xliff  Fortunately, this new file is very small. Thanks.

**Comment by bocharsky-bw** [comment]
I missed it possibly. I'll create it soon

**Comment by bocharsky-bw** [comment]
@javiereguiluz I finished.

**Comment by javiereguiluz** [comment]
great! Another finished translation. @bocharsky-bw thanks a lot for your work!

**Pull request closed without merging**
