### PR TITLE
Fix web check filename

### PR DESCRIPTION
**Pull request by bocharsky-bw**
We renamed `web/config.php` to `web/check.php` in https://github.com/symfony/symfony-demo/pull/74

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Good catch, thanks @bocharsky-bw.

**Comment by bocharsky-bw** [comment]
@javiereguiluz Wow, sorry, but it's look like this file override every time when we run `Composer`. The source file located in [app/check.php](https://github.com/sensiolabs/SensioDistributionBundle/blob/78faf147315523aaa5c3fefbe6a0e57d2f6745d3/Resources/skeleton/app/check.php#L71)

Maybe better live `app/config.php`? What do you think?

**Comment by stof** [comment]
Well, this file is updated from SensioDistributionBundle by a composer hook. So there is 2 solutions:

- keep the file unmodified
- remove the composer hook updating the requirement checker

**Comment by bocharsky-bw** [comment]
I hesitate what would be better.

**Comment by xabbuh** [comment]
Well, the hook does not only install the `app/check.php` file, but also updates the `app/SymfonyRequirements.php` file which contains the actual rules which can be more often subject to changes. Changing the file in the `web` directory is possibly the better solution.

**Comment by bocharsky-bw** [comment]
Maybe we should rename `web/check.php` to `web/config.php` to be consistent with Symfony Standard?

**Comment by xabbuh** [comment]
@bocharsky-bw Imo that's the best solution.

**Comment by bocharsky-bw** [comment]
I agree with you.
@javiereguiluz What do you think?

**Pull request merged**
