### PR TITLE
Updated sensio/distribution-bundle dependency to fix loading PHP extensions twice

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Related to the https://github.com/sensiolabs/SensioDistributionBundle/issues/299

Current version of `sensio/distribution-bundle` with Composer 1.3 throws warnings on composer install/update:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0

 // Clearing the cache for the dev environment with debug
 // true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0

 Trying to install assets as relative symbolic links.

 --- ------------------------------ ------------------
      Bundle                         Method / Error
 --- ------------------------------ ------------------
  ✔   WhiteOctoberPagerfantaBundle   relative symlink
 --- ------------------------------ ------------------


 [OK] All assets were successfully installed.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I appreciate your efforts to fix this problem ... but shouldn't we wait for a fix upstream? I don't think we should modify this file ourselves.

**Comment by stof** [comment]
this must indeed be fixed in SensioDistributionBundle. Otherwise the fix would be lost on the next ``composer update`` (or even ``composer install`` btw IIRC)

**Comment by bocharsky-bw** [comment]
@javiereguiluz Yes, you're definitely right but you misunderstand me. The `sensio/distribution-bundle` `v5.0.17` is already released. Those changes were made by Composer, not by me. Check the composer.lock suppressed diff

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks! I understand this PR now. I've updated the title to make it easier to understand.

👍

**Comment by bocharsky-bw** [comment]
@javiereguiluz Much better, thanks!

**Comment by javiereguiluz** [comment]
Thanks for fixing this issue. It's merged now.

**Pull request merged**
